import { useState } from "react";
import { ChevronDown, ChevronRight } from "lucide-react";

const sections = [
  {
    title: "Containers",
    classes: [
      "container",
      "container-fluid",
      "container-sm",
      "container-md",
      "container-lg",
      "container-xl",
      "container-xxl",
    ],
  },
  {
    title: "Grid — Columns",
    classes: [
      "row",
      "col-sm-1",
      "col-sm-2",
      "col-sm-3",
      "col-sm-4",
      "col-sm-5",
      "col-sm-6",
      "col-sm-7",
      "col-sm-8",
      "col-sm-9",
      "col-sm-10",
      "col-sm-11",
      "col-sm-12",
      "col-md-1",
      "col-md-2",
      "col-md-3",
      "col-md-4",
      "col-md-5",
      "col-md-6",
      "col-md-7",
      "col-md-8",
      "col-md-9",
      "col-md-10",
      "col-md-11",
      "col-md-12",
      "col-lg-1",
      "col-lg-2",
      "col-lg-3",
      "col-lg-4",
      "col-lg-5",
      "col-lg-6",
      "col-lg-7",
      "col-lg-8",
      "col-lg-9",
      "col-lg-10",
      "col-lg-11",
      "col-lg-12",
    ],
  },
  {
    title: "Grid — Offsets",
    classes: [
      "offset-0",
      "offset-1",
      "offset-2",
      "offset-3",
      "offset-4",
      "offset-5",
      "offset-6",
      "offset-7",
      "offset-8",
      "offset-9",
      "offset-10",
      "offset-11",
      "offset-sm-0",
      "offset-sm-1",
      "offset-sm-2",
      "offset-sm-3",
      "offset-sm-4",
      "offset-sm-5",
      "offset-sm-6",
      "offset-sm-7",
      "offset-sm-8",
      "offset-sm-9",
      "offset-sm-10",
      "offset-sm-11",
      "offset-md-0",
      "offset-md-1",
      "offset-md-2",
      "offset-md-3",
      "offset-md-4",
      "offset-md-5",
      "offset-md-6",
      "offset-md-7",
      "offset-md-8",
      "offset-md-9",
      "offset-md-10",
      "offset-md-11",
      "offset-lg-0",
      "offset-lg-1",
      "offset-lg-2",
      "offset-lg-3",
      "offset-lg-4",
      "offset-lg-5",
      "offset-lg-6",
      "offset-lg-7",
      "offset-lg-8",
      "offset-lg-9",
      "offset-lg-10",
      "offset-lg-11",
    ],
  },
  {
    title: "Display",
    classes: [
      "d-none",
      "d-block",
      "d-inline",
      "d-inline-block",
      "d-flex",
      "d-inline-flex",
      "d-grid",
      "d-sm-none",
      "d-sm-block",
      "d-sm-flex",
      "d-md-none",
      "d-md-block",
      "d-md-flex",
      "d-lg-none",
      "d-lg-block",
      "d-lg-flex",
    ],
  },
  {
    title: "Flexbox",
    classes: [
      "flex-row",
      "flex-row-reverse",
      "flex-column",
      "flex-column-reverse",
      "flex-wrap",
      "flex-nowrap",
      "flex-wrap-reverse",
      "flex-fill",
      "flex-1",
      "flex-none",
      "flex-auto",
      "flex-initial",
      "flex-grow-0",
      "flex-grow-1",
      "flex-shrink-0",
      "flex-shrink-1",
      "justify-content-start",
      "justify-content-end",
      "justify-content-center",
      "justify-content-between",
      "justify-content-around",
      "justify-content-evenly",
      "align-items-start",
      "align-items-end",
      "align-items-center",
      "align-items-baseline",
      "align-items-stretch",
      "align-content-start",
      "align-content-end",
      "align-content-center",
      "align-content-between",
      "align-content-around",
      "align-content-stretch",
      "align-self-start",
      "align-self-end",
      "align-self-center",
      "align-self-stretch",
    ],
  },
  {
    title: "Flex + Gap Shortcuts",
    classes: [
      "fdc-gap-0",
      "fdc-gap-1",
      "fdc-gap-2",
      "fdc-gap-3",
      "fdc-gap-4",
      "fdc-gap-5",
      "fdr-gap-0",
      "fdr-gap-1",
      "fdr-gap-2",
      "fdr-gap-3",
      "fdr-gap-4",
      "fdr-gap-5",
      "fdcr-gap-0",
      "fdcr-gap-1",
      "fdcr-gap-2",
      "fdcr-gap-3",
      "fdcr-gap-4",
      "fdcr-gap-5",
      "fdrr-gap-0",
      "fdrr-gap-1",
      "fdrr-gap-2",
      "fdrr-gap-3",
      "fdrr-gap-4",
      "fdrr-gap-5",
    ],
  },
  {
    title: "Padding",
    classes: [
      "p-0",
      "p-1",
      "p-2",
      "p-3",
      "p-4",
      "p-5",
      "px-0",
      "px-1",
      "px-2",
      "px-3",
      "px-4",
      "px-5",
      "py-0",
      "py-1",
      "py-2",
      "py-3",
      "py-4",
      "py-5",
      "pt-0",
      "pt-1",
      "pt-2",
      "pt-3",
      "pt-4",
      "pt-5",
      "pb-0",
      "pb-1",
      "pb-2",
      "pb-3",
      "pb-4",
      "pb-5",
      "ps-0",
      "ps-1",
      "ps-2",
      "ps-3",
      "ps-4",
      "ps-5",
      "pe-0",
      "pe-1",
      "pe-2",
      "pe-3",
      "pe-4",
      "pe-5",
    ],
  },
  {
    title: "Margin",
    classes: [
      "m-0",
      "m-1",
      "m-2",
      "m-3",
      "m-4",
      "m-5",
      "m-auto",
      "mt-0",
      "mt-1",
      "mt-2",
      "mt-3",
      "mt-4",
      "mt-5",
      "mt-auto",
      "mb-0",
      "mb-1",
      "mb-2",
      "mb-3",
      "mb-4",
      "mb-5",
      "mb-auto",
      "ml-0",
      "ml-1",
      "ml-2",
      "ml-3",
      "ml-4",
      "ml-5",
      "ml-auto",
      "mr-0",
      "mr-1",
      "mr-2",
      "mr-3",
      "mr-4",
      "mr-5",
      "mr-auto",
      "mx-0",
      "mx-1",
      "mx-2",
      "mx-3",
      "mx-4",
      "mx-5",
      "mx-auto",
      "my-0",
      "my-1",
      "my-2",
      "my-3",
      "my-4",
      "my-5",
      "my-auto",
    ],
  },
  {
    title: "Margin — Mobile",
    classes: [
      "m-m-0",
      "m-m-1",
      "m-m-2",
      "m-m-3",
      "m-m-4",
      "m-m-5",
      "mt-m-0",
      "mt-m-1",
      "mt-m-2",
      "mt-m-3",
      "mt-m-4",
      "mt-m-5",
      "mb-m-0",
      "mb-m-1",
      "mb-m-2",
      "mb-m-3",
      "mb-m-4",
      "mb-m-5",
      "ml-m-0",
      "ml-m-1",
      "ml-m-2",
      "ml-m-3",
      "ml-m-4",
      "ml-m-5",
      "mr-m-0",
      "mr-m-1",
      "mr-m-2",
      "mr-m-3",
      "mr-m-4",
      "mr-m-5",
      "mx-m-0",
      "mx-m-1",
      "mx-m-2",
      "mx-m-3",
      "mx-m-4",
      "mx-m-5",
      "my-m-0",
      "my-m-1",
      "my-m-2",
      "my-m-3",
      "my-m-4",
      "my-m-5",
    ],
  },
  {
    title: "Sizing",
    classes: [
      "w-0",
      "w-25",
      "w-50",
      "w-75",
      "w-100",
      "w-auto",
      "h-0",
      "h-25",
      "h-50",
      "h-75",
      "h-100",
      "h-auto",
      "min-w-0",
      "min-w-25",
      "min-w-50",
      "min-w-75",
      "min-w-100",
      "min-w-auto",
      "max-w-0",
      "max-w-25",
      "max-w-50",
      "max-w-75",
      "max-w-100",
      "max-w-auto",
      "min-h-0",
      "min-h-25",
      "min-h-50",
      "min-h-75",
      "min-h-100",
      "min-h-auto",
      "min-vh-25",
      "min-vh-50",
      "min-vh-75",
      "min-vh-100",
      "max-h-0",
      "max-h-25",
      "max-h-50",
      "max-h-75",
      "max-h-100",
      "max-h-auto",
      "vidyard-frame-w",
    ],
  },
  {
    title: "Typography — Size & Weight",
    classes: [
      "text-xs",
      "text-sm",
      "text-base",
      "text-md",
      "text-lg",
      "text-xl",
      "text-2xl",
      "text-3xl",
      "text-4xl",
      "text-5xl",
      "fw-light",
      "fw-normal",
      "fw-medium",
      "fw-semibold",
      "fw-bold",
    ],
  },
  {
    title: "Typography — Alignment & Transform",
    classes: [
      "text-left",
      "text-center",
      "text-right",
      "text-justify",
      "text-uppercase",
      "text-lowercase",
      "text-capitalize",
      "text-normal-case",
      "text-wrap",
      "text-nowrap",
      "text-break",
      "text-break-all",
      "text-keep",
      "text-hyphen",
      "text-decoration-none",
      "text-decoration-underline",
    ],
  },
  {
    title: "Text Colors",
    classes: [
      "text-ink-blue",
      "text-heritage",
      "text-link",
      "text-white",
      "text-gold",
      "text-link-drk",
      "link-dark-blue",
      "link-unset",
      "ink-blue",
      "heritage",
    ],
  },
  {
    title: "Background — Colors",
    classes: [
      "bg-ink-blue",
      "bg-heritage",
      "bg-sky",
      "bg-light-blue",
      "bg-gold",
      "bg-link",
      "bg-white",
      "bg-lightgray",
      "bg-tan",
    ],
  },
  {
    title: "Background — Images",
    classes: [
      "img-1",
      "pattern-blue-bg",
      "wolak-center-header-bg",
      "weekly-planner-bg",
    ],
  },
  {
    title: "Background — Position & Size",
    classes: ["bg-container", "bg-pos-top", "bg-pos-bottom", "bg-pos-center"],
  },
  {
    title: "Borders & Radius",
    classes: [
      "border-ink-blue",
      "border-heritage",
      "border-link",
      "border-lightgray",
      "border-white",
      "brdr-rad-20",
      "gold-shadow",
      "rad-tr-bl",
      "rad-tl-br",
      "rad-tl-br-60",
      "rad-tr-bl-60",
    ],
  },
  {
    title: "Position & Z-Index",
    classes: [
      "position-static",
      "position-relative",
      "position-absolute",
      "position-fixed",
      "position-sticky",
      "top-0",
      "top-50",
      "top-100",
      "bottom-0",
      "bottom-50",
      "bottom-100",
      "start-0",
      "start-50",
      "start-100",
      "end-0",
      "end-50",
      "end-100",
      "translate-middle",
      "translate-middle-x",
      "translate-middle-y",
      "inset-0",
      "z-n1",
      "z-0",
      "z-1",
      "z-10",
      "z-100",
      "z-1000",
    ],
  },
  {
    title: "Buttons",
    classes: [
      "btn",
      "btn-rounded",
      "btn-corner",
      "btn-primary",
      "btn-secondary",
      "btn-no-outline",
      "btn-link",
    ],
  },
  {
    title: "Cards",
    classes: [
      "card",
      "card-col",
      "card-simple",
      "card-video",
      "rounded-card",
      "number-card",
    ],
  },
  {
    title: "Navigation",
    classes: [
      "nav",
      "nav-item",
      "nav-link",
      "navbar-bg-white",
      "navbar-bg-blue",
      "countdown-nav",
    ],
  },
  {
    title: "Accordion",
    classes: [
      "accordion",
      "accordion-flush",
      "accordion-item",
      "accordion-header",
      "accordion-button",
      "accordion-collapse",
      "accordion-body",
    ],
  },
  {
    title: "Icons",
    classes: [
      "todo-icon",
      "number-icon",
      "info-icon",
      "arrow",
      "star",
      "one",
      "two",
      "three",
      "four",
      "five",
      "academic",
      "campus",
      "wellness",
      "career",
      "wolak",
      "public",
      "residence",
      "involvement",
      "employment",
    ],
  },
  {
    title: "Components",
    classes: [
      "todo-wrapper",
      "upcoming-date-table",
      "footer-flush",
      "logo-blue-text",
      "logo-white-text",
      "hr-2",
    ],
  },
  {
    title: "Page — Advisor Handoff",
    classes: [
      "overlap-content",
      "header-content",
      "form-content",
      "form-placeholder",
      "contact-preference",
      "contact-option",
      "contact-check",
    ],
  },
];

const CssReference = () => {
  const [open, setOpen] = useState<string | null>(null);

  return (
    <div className="h-full overflow-y-auto p-3 text-sm">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground mb-3">
        CSS Classes
      </h3>
      {sections.map((s) => (
        <div key={s.title} className="mb-1">
          <button
            onClick={() => setOpen(open === s.title ? null : s.title)}
            className="flex items-center gap-1 w-full py-1.5 px-2 rounded text-secondary-foreground hover:bg-secondary/50 transition-colors text-left"
          >
            {open === s.title ? (
              <ChevronDown className="w-3 h-3" />
            ) : (
              <ChevronRight className="w-3 h-3" />
            )}
            <span className="font-medium">{s.title}</span>
            <span className="text-muted-foreground ml-auto text-xs">
              {s.classes.length}
            </span>
          </button>
          {open === s.title && (
            <div className="flex flex-wrap gap-1 px-2 py-2">
              {s.classes.map((c) => (
                <code
                  key={c}
                  className="text-xs bg-secondary px-1.5 py-0.5 rounded text-primary font-mono"
                >
                  .{c}
                </code>
              ))}
            </div>
          )}
        </div>
      ))}
    </div>
  );
};

export default CssReference;
